### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by AdnanInayat** [TokenySolutions/T-REX#117]
Hi,

I am trying to develop this solution but the I find it quite difficult because of the outdated documentation from TREX. Can't even install the package if you follow the documentation. 
I install the package from the reference given here on github. But still import doesn't work. I tried to change the SOL default package dependencies but still no luck. 
Is it still maintained or not?
I can see last commits were almost a year ago and documentation last edited almost 2 years ago.

**Comment by Joachim-Lebrun** [comment]
can you be more clear? which documentation exactly are you referring to? 
Regarding commits on the main branch we are waiting for the v4 update to commit again on main branch but if you check other branches, there is work in progress to make the v4 release which should be ready very soon and will be merged in the main branch once it has been audited by an external company.

**Comment by AdnanInayat** [comment]
I am currently following this one:
https://docs.tokeny.com/docs/t-rex-sdk
But even the main package @tokenyico/trx-sdk isn't available. It gives error on npm install. 
I am attaching screenshot. Have a look :)

![npm-install-fail](https://user-images.githubusercontent.com/14906015/188671174-42ea6bcd-9558-444b-909d-7a2005ea101f.png)

**Comment by Joachim-Lebrun** [comment]
If you read the documentation at https://docs.tokeny.com/docs/t-rex-sdk you will see that it is clearly mentioned as following : 
> Important Note To be able to download the package, you need to have read access to the repository of the TREX SDK.

The TREX SDK repository is not yet available in open source and therefore you don't have read access to it, that's why it fails. 
In the meantime the current issue was created on the TREX repository containing the smart contracts and regarding an issue that is not linked to the smart contracts, i will then close the issue.
