### ISSUE TITLE
Should issuer be either the Identity itself or the ClaimIssuer?

### ISSUE THREAD

**Issue by Web3Prof** [TokenySolutions/T-REX#203]
`Claim` has `issuer` property which should be an ONCHAINID address. `Issuer` should be an instance of `ClaimIssuer` or ONCHAINID with key purpose of 1 or 3, but since the `isClaimValid` is checking on the issuer's contract and inside the function it checks the `keyHasPurpose` . All instance of an Identity has the `isClaimValid` signature, so even if it's not a `ClaimIssuer` contract, it will return `true` because it has the correct signature and `keyHasPurpose` will always have a key purpose of one because the signer wallet address (that is retrieved from the `getRecoveredAddress`) is the initial key management of the issuer's identity.

```
if(_issuer != address(this)) {
            require(IClaimIssuer(_issuer).isClaimValid(IIdentity(address(this)), _topic, _signature, _data), "invalid claim"); // go to
        }
```

To solve this issue (to check that issuer is not some random ONCHAINID), I propose to add a function to check the key purpose on the claim receiver ONCHAINID `isIssuerValid` if the issuer is not self-attested, it must have the key purpose of 3 or check if address is an instance of `ClaimIssuer' by adding a function of `isClaimIssuer` in IClaimIssuer contract.

Minor bug: In the require part of checking the number of topics in `Verifier.sol`, it should be less than equal.
```
require(length <= 15, "cannot require more than 15 topics");
```

**Comment by Nakasar** [comment]
Hello, and welcome!

The `claim.issuer` property only needs to target a contract address that have the `isClaimValid` method (not especially a full ClaimIssuer or event not a full Identity), because the identity registry will call only the `isClaimValid` method. Validating the claim is left at the discretion of the target contract (some may validate their own signature, maintain a list of claim, or any other method).


We added the `isClaimValid` method to the Identity base contract to support self-attested claims (so that a smart contract or an off-chain verifier willing to verify a claim doesn't have to separate between claims from claim issuers and self-issued claims).


Self-issued/self-attested claims are proof an identity owner can declare on their own and sign, storing them on-chain or off-chain while still allowing verifiers to verify them.
For instance identities may want to self-declare a domain name, profile picture, services, related identities, ...


In general when token issuers want a specific claim issued by a list of issuers they trust, they will specify this list on the token Trusted Issuers Registry (therefore a self-attested claim will never be accepted by the Identity Registry because the identity address is most probably not in this trusted issuers array).


We can't "trust" Identities implementation because they might not be our ONCHAINID implementation, so the result of the `isClaimValid` on an identity cannot be trusted for verifying claims other than claims issued by the contract itself.

I fell like I was not very clear, don't hesitate if it wasn't!

**Comment by Web3Prof** [comment]
Hi, thanks for the reply! Well understood, thank you very much for the explanation. Just want to say the T-REX itself has a lot of component so I might not fully understand the whole intention and correlation of each element. Again, thanks for the explanation!
