### ISSUE TITLE
only Factory or owner can call

### ISSUE THREAD

**Issue by LyghtCode** [TokenySolutions/T-REX#217]
`Deploying contracts with the account: 0xCC424D4af7Add42Bed4aE68E27A1547EE81173B1
Implementation Authority already deployed at: 0x9aa885Bf5E845d20766BB6cc408516DFb77EDC56
Token Implementation already deployed at: 0xDe419f2d122C40cf16A36dBc11916bc4089EdBA5
Claim Topics Registry Implementation already deployed at: 0x73b36629F09237ACbC6d91a453d31b5beD9654A2
Identity Registry Implementation already deployed at: 0x417ee07587c0Daf95f61E4264a7BD60f9b8Ee7B2
Identity Registry Storage Implementation already deployed at: 0xB8be78F2B33eB298e10e43419b47F570b10fd01A
Modular Compliance Implementation already deployed at: 0x5A51bcAe72DF4b30792Dd669880361dD507Ae3C1
Trusted Issuers Registry Implementation already deployed at: 0x07d6C9dD63697647E02860BA0cF5b11159956247
Version already exists in Implementation Authority
Identity Factory already deployed at: 0x974BE5634a016721535fC157EA531dB11ED046F0
TREXFactory already deployed at: 0xEF7fa56dA603796381868Bb6d93feCd3f7857628
TREXGateway already deployed at: 0xa9fB792a60eceAfB4977147B57C85c87B4DD7688
TREXFactory owner: 0xa9fB792a60eceAfB4977147B57C85c87B4DD7688
TREXGateway owner: 0xCC424D4af7Add42Bed4aE68E27A1547EE81173B1
Is deployer: true
Is TREXFactory a deployer: false
Adding TREXFactory as a deployer to TREXGateway...
TREXFactory added as a deployer to TREXGateway.
TREXFactory set in Implementation Authority
Deploying TREX Suite...`

If im not mistaken Gateway is owned by deployer and factory should be owned by Gateway? I keep running into only Factory or owner can call

Current Deploy Script:
[Gist](https://gist.github.com/LyghtCode/ada3bf5af03ea5c05dae23dbec9dc69b)

**Comment by Joachim-Lebrun** [comment]
hello, your error comes from IdFactory, not from TREXFactory, you try to deploy an ONCHAINID for the token but you didn't configure your IdFactory at all. 
You need to : 
- deploy Identity implem
- deploy ImplementationAuthority for the IdFactory 
- set ImplementationAuthority properly on the factory 
- set TREXFactory as a token factory, allowing it to call token identity deployments 

a quick fix otherwise is to give a random address for onchainid when you create a token, this way it doesn't try to create a new OID for the token and it uses that address instead, but it is not good practice. could be used to check that this is indeed the issue though
