### ISSUE TITLE
Add safety check on UpdatedTokenInformation

### ISSUE THREAD

**Issue by ernaneluis** [TokenySolutions/T-REX#27]
based on this thread:
https://github.com/tokenyICO/trex-subgraph/pull/5#pullrequestreview-326699216

it should block the token owner to change the decimals if transfers has been done. it should only allow the change of decimals  before any token is minted and/or transfered

**Comment by Joachim-Lebrun** [comment]
this issue is solved in TREX 3.0 as there is no setter for `decimals` or `version` anymore, instead of a big setter for all infos at the same time we created 3 separate setters for name, symbol and onchainID. Other state variables(decimals and version) are initiated in the constructor and should not be changed post-deployment
